/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/context/UserContext`; params?: Router.UnknownInputParams; } | { pathname: `/DB_Save/dataBase`; params?: Router.UnknownInputParams; } | { pathname: `/lib/storage`; params?: Router.UnknownInputParams; } | { pathname: `/screen/Home`; params?: Router.UnknownInputParams; } | { pathname: `/screen/Onboarding`; params?: Router.UnknownInputParams; } | { pathname: `/screen/Profile`; params?: Router.UnknownInputParams; } | { pathname: `/screen/Splash`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/context/UserContext`; params?: Router.UnknownOutputParams; } | { pathname: `/DB_Save/dataBase`; params?: Router.UnknownOutputParams; } | { pathname: `/lib/storage`; params?: Router.UnknownOutputParams; } | { pathname: `/screen/Home`; params?: Router.UnknownOutputParams; } | { pathname: `/screen/Onboarding`; params?: Router.UnknownOutputParams; } | { pathname: `/screen/Profile`; params?: Router.UnknownOutputParams; } | { pathname: `/screen/Splash`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/context/UserContext${`?${string}` | `#${string}` | ''}` | `/DB_Save/dataBase${`?${string}` | `#${string}` | ''}` | `/lib/storage${`?${string}` | `#${string}` | ''}` | `/screen/Home${`?${string}` | `#${string}` | ''}` | `/screen/Onboarding${`?${string}` | `#${string}` | ''}` | `/screen/Profile${`?${string}` | `#${string}` | ''}` | `/screen/Splash${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/context/UserContext`; params?: Router.UnknownInputParams; } | { pathname: `/DB_Save/dataBase`; params?: Router.UnknownInputParams; } | { pathname: `/lib/storage`; params?: Router.UnknownInputParams; } | { pathname: `/screen/Home`; params?: Router.UnknownInputParams; } | { pathname: `/screen/Onboarding`; params?: Router.UnknownInputParams; } | { pathname: `/screen/Profile`; params?: Router.UnknownInputParams; } | { pathname: `/screen/Splash`; params?: Router.UnknownInputParams; };
    }
  }
}
